global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "lsmkv"
    static_configs:
      - targets:
          - "node0:9001"
          - "node1:9002"
          - "node2:9003"
